name: compile-test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup Java 21
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          java-version: '21'
          distribution: 'adopt'
      - uses: sbt/setup-sbt@4d1c55d37e6b6207c2952be12394058d9b6e4aa1 # v1.1.3
      - run: sbt test
