name: compile-test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Java 21
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '21'
          distribution: 'adopt'
      - uses: sbt/setup-sbt@4d1c55d37e6b6207c2952be12394058d9b6e4aa1 # v1.1.3
      - run: sbt test
