name: Release Container Image

on:
    release:
        types: [published]

jobs:
    build-and-publish:
        name: Build and Publish Container Image
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
          with:
            platforms: linux/amd64,linux/arm64

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push Container image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: |
                ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.event.release.tag_name }}
                ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            platforms: linux/amd64,linux/arm64